### ISSUE TITLE
Kro is currently in alpha and 'ResourceGroup' appears to be removed

### ISSUE THREAD

**Issue by martinborgman** [vfarcic/kro-vs-helm#2]
As you mention in the article, the kro project is in it's very early stages and it appears they replaced 'ResourceGroup' by 'ResourceGraphDefinition'.

k8s/kro.yaml should start like this:
```yaml
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: application
spec:
...
```
